# Generated by Django 4.2.29 on 2026-03-09 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("purchase", "Purchase"), ("sale", "Sale")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("quantity_change", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stock_transactions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="stock_trans_timesta_ad001e_idx"
                    ),
                    models.Index(
                        fields=["product", "-timestamp"],
                        name="stock_trans_product_c93182_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="stock_trans_transac_b2b788_idx",
                    ),
                ],
            },
        ),
    ]
