# Generated by Django 4.2.29 on 2026-03-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_stocktransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("request_data", models.JSONField()),
                ("response_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "ai_interaction_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LowStockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "db_table": "low_stock_alerts",
                "indexes": [
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="low_stock_a_is_acti_2332b1_idx",
                    )
                ],
            },
        ),
    ]
